<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MonoTorrent\MonoTorrent.csproj" />
    <ProjectReference Include="..\..\MonoTorrent.Client\MonoTorrent.Client.csproj" />
  </ItemGroup>

</Project>
